const {chromium}=require('/opt/homebrew/lib/node_modules/agent-browser/node_modules/playwright-core'),assert=require('node:assert/strict'),{randomBytes}=require('node:crypto');
(async()=>{const root=process.env.ENTRY_URL||'http://127.0.0.1:8065/play/',origin=new URL(root).origin;if(!['127.0.0.1','localhost'].includes(new URL(root).hostname))throw Error('Local throwaway account test only');const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--enable-webgl','--use-angle=metal']});try{
const c=await b.newContext({viewport:{width:1280,height:850},hasTouch:true}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));const signup=await c.request.post(root+'api/accounts/signup',{headers:{Origin:origin,'X-Pawtheon-Request':'1'},data:{username:'maze86_'+randomBytes(6).toString('hex'),password:randomBytes(30).toString('base64url'),name:'Maze test'}});assert.equal(signup.status(),200);
await p.route(/\/game\.js(?:\?.*)?$/,async route=>{const r=await route.fetch();await route.fulfill({response:r,body:await r.text()+'\nglobalThis.mazeAudit={sunwardMaze,player,rewards:[]};addEventListener("paw-minigame-xp",e=>mazeAudit.rewards.push(e.detail));'});});
await p.goto(root);await p.click('#entrySingle');await p.waitForFunction(()=>globalThis.mazeAudit&&!document.getElementById('loading'),null,{timeout:180000});await p.evaluate(async()=>{const s=mazeAudit.sunwardMaze.site,{height}=await import('./geography.js');mazeAudit.player.position.set(s.x,height(s.x,s.z),s.z);});await p.click('#mazeEnter');await p.selectOption('#sunMaze select','86');
assert.equal(await p.evaluate(()=>mazeAudit.sunwardMaze.state.cells),86);assert.equal(await p.evaluate(()=>mazeAudit.sunwardMaze.state.size),173);await p.evaluate(()=>mazeAudit.rewards=[]);const staticBefore=await p.evaluate(()=>mazeAudit.sunwardMaze.view.staticBuilds);await p.waitForTimeout(300);assert.equal(await p.evaluate(()=>mazeAudit.sunwardMaze.view.staticBuilds),staticBefore);
await p.click('#sunMaze [data-action="zoom-in"]');assert.equal(await p.evaluate(()=>mazeAudit.sunwardMaze.view.tiles),17);await p.click('#sunMaze [data-action="zoom-in"]');assert.equal(await p.evaluate(()=>mazeAudit.sunwardMaze.view.tiles),11);await p.click('#sunMaze [data-action="overview"]');assert.equal(await p.evaluate(()=>mazeAudit.sunwardMaze.view.fullMap),true);
const direction=await p.evaluate(()=>{const s=mazeAudit.sunwardMaze.state;return [[1,0],[0,1]].find(([dx,dy])=>s.grid[s.y+dy][s.x+dx]===0)});await p.locator('#sunMaze .maze-board').focus();await p.keyboard.press(direction[0]?'ArrowRight':'ArrowDown');assert.equal(await p.evaluate(()=>mazeAudit.sunwardMaze.state.moves),1);assert.equal(await p.evaluate(()=>mazeAudit.sunwardMaze.view.fullMap),false);assert.equal(await p.evaluate(()=>mazeAudit.sunwardMaze.view.staticBuilds),staticBefore);
for(const [width,height]of [[1280,850],[1024,768],[768,1024],[390,844],[320,700]]){await p.setViewportSize({width,height});await p.waitForTimeout(100);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert(await p.locator('#sunMaze .maze-board').isVisible());assert(await p.locator('#sunMaze .maze-overview').isVisible());const box=await p.locator('#sunMaze .maze-board').boundingBox();assert(Math.min(box.width,box.height)>=200);await p.locator('#sunMaze [data-dir="0,1"]').scrollIntoViewIfNeeded();assert(await p.locator('#sunMaze [data-dir="0,1"]').isVisible());}
await p.setViewportSize({width:1024,height:768});await p.locator('#sunMaze .maze-board').scrollIntoViewIfNeeded();await p.screenshot({path:'/tmp/paw-maze86-ipad.png'});
// Place the deterministic test run at the final legal corridor tile; full path correctness is covered in maze86.mjs.
await p.evaluate(()=>{const s=mazeAudit.sunwardMaze.state;s.x=s.exit.x-1;s.y=s.exit.y;});await p.locator('#sunMaze .maze-board').focus();await p.keyboard.press('ArrowRight');await p.waitForFunction(()=>mazeAudit.sunwardMaze.state.won);assert.match(await p.locator('#sunMaze .maze-result').textContent(),/You escaped/);assert.equal(await p.evaluate(()=>mazeAudit.rewards.length),0);const count=await p.evaluate(async()=>{const {readMinigameRecords}=await import('./minigame-records.js');return readMinigameRecords().records.maze86.count;});assert.equal(count,1);await p.keyboard.press('ArrowRight');assert.equal(await p.evaluate(async()=>{const {readMinigameRecords}=await import('./minigame-records.js');return readMinigameRecords().records.maze86.count;}),1);assert.deepEqual(errors,[]);console.log('PASS173grid, static cache reuse, zoom/follow/full overview, keyboard move, desktop/iPad/phone viewport, single completion record and no new XP; zero JS errors');
}finally{await b.close();}})().catch(e=>{console.error(e.message);process.exit(1)});
