import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {randomBytes} from 'node:crypto';
import {openRoomDatabase} from '../scripts/preview-database.mjs';import worker from '../worker/index.js';
import {minigameRecords,captureBoatResults,captureLavaResults} from '../worker/minigame-records.js';
import {boatRequest} from '../worker/boat-races.js';import {lavaRequest} from '../worker/lava-arena.js';
import {newBoatRace} from '../public/boat-race-core.js';import {BOAT_COURSE_VERSION} from '../public/boat-course-layout.js';
import {newArena,arenaPlayer} from '../public/lava-arena-core.js';
const dir=await mkdtemp(join(tmpdir(),'paw-minigame-ledger-')),file=join(dir,'db.sqlite');let db=openRoomDatabase(file);const now=Date.now(),origin='https://test.example';
async function api(path,body,cookie='',token=''){const r=await worker.fetch(new Request(origin+'/api/'+path,{method:body?'POST':'GET',headers:{Origin:origin,Cookie:cookie,Authorization:'Bearer '+token,'Content-Type':'application/json','X-Pawtheon-Request':'1'},...(body?{body:JSON.stringify(body)}:{})}),{DB:db.DB});return {status:r.status,data:await r.json(),cookie:r.headers.get('Set-Cookie')?.split(';')[0]};}
try{
const signup=()=>api('accounts/signup',{username:'records_'+randomBytes(6).toString('hex'),password:randomBytes(30).toString('base64url'),name:'Record tester'});const a=await signup(),b=await signup();assert.equal(a.status,200);assert.equal(b.status,200);const profile='account:'+a.data.user.id;
const created=await api('multiplayer/create',{},a.cookie),room=created.data.room,state={dog:5035,x:0,y:0,z:15,yaw:0};const pa=await api('multiplayer/join',{room,state},a.cookie),pb=await api('multiplayer/join',{room,state},b.cookie);const at=pa.data.token,bt=pb.data.token;
assert.equal((await api('accounts/minigame-records')).status,401);assert.equal((await api('accounts/minigame-records',{accountId:a.data.user.id,game:'boat',time:0.1},a.cookie)).status,404);
const race={id:'boat-ledger',phase:'racing',startsAt:now-100000,course:BOAT_COURSE_VERSION,host:at.slice(0,16)};
await db.DB.prepare('INSERT INTO multiplayer_boat_races(room,state) VALUES(?,?)').bind(room,JSON.stringify(race)).run();
for(const [token,time]of [[at,80],[bt,90]]){const s=newBoatRace(0);s.done=true;s.time=time;await db.DB.prepare("INSERT INTO multiplayer_boat_entries(room,player,race,name,dog,state,seq,status,updated,finished) VALUES(?,?,?,?,?,?,10,'finished',?,?)").bind(room,token.slice(0,16),race.id,'Record tester',5035,JSON.stringify(s),now,time).run();}
assert(!(await boatRequest(db.DB,room,at,{action:'state'},now)).error);
let result=await minigameRecords(db.DB,profile);assert.equal(result.verified.boat.games,1);assert.equal(result.verified.boat.bestTime,80);assert.equal(result.verified.boat.wins,1);
await boatRequest(db.DB,room,at,{action:'state',finished:0.01,time:0.01},now);await boatRequest(db.DB,room,at,{action:'leave',race:race.id},now);result=await minigameRecords(db.DB,profile);assert.equal(result.verified.boat.games,1);assert.equal(result.verified.boat.bestTime,80);assert.equal(result.verified.boat.wins,1);
const round=newArena('lava-ledger',now);Object.assign(round,{phase:'finished',startsAt:now-60000,tickAt:now,players:[{...arenaPlayer(at.slice(0,16),'A',5035,0,now),status:'alive'},{...arenaPlayer(bt.slice(0,16),'B',5035,1,now),status:'out'}],winners:[at.slice(0,16)]});await db.DB.prepare('INSERT INTO multiplayer_lava_arenas(room,state) VALUES(?,?)').bind(room,JSON.stringify(round)).run();assert(!(await lavaRequest(db.DB,room,at,{action:'state'},now)).error);await lavaRequest(db.DB,room,at,{action:'state',won:false,score:9000000},now);
result=await minigameRecords(db.DB,profile);assert.equal(result.verified.lava.games,1);assert.equal(result.verified.lava.wins,1);assert.equal(result.leaders.lava[0].self,true);assert.equal((await minigameRecords(db.DB,'account:'+b.data.user.id)).verified.lava.losses,1);
const tied={...round,id:'lava-tie',winners:[at.slice(0,16),bt.slice(0,16)],players:round.players.map(p=>({...p,status:'alive'}))};await captureLavaResults(db.DB,room,tied);result=await minigameRecords(db.DB,profile);assert.equal(result.verified.lava.draws,1);
const left={...round,id:'lava-left',players:round.players.map(p=>({...p,status:'left'})),winners:[]};await captureLavaResults(db.DB,room,left);assert.equal((await minigameRecords(db.DB,profile)).verified.lava.games,2);
const departingRace={...race,id:'boat-departure'};const departingEntries=[{player:at.slice(0,16),status:'finished',finished:100},{player:bt.slice(0,16),status:'racing',finished:null}];await captureBoatResults(db.DB,room,departingRace,departingEntries);const oldPlayer=await db.DB.prepare('SELECT * FROM multiplayer_players WHERE token=?').bind(at).first();await db.DB.prepare('DELETE FROM multiplayer_players WHERE token=?').bind(at).run();departingEntries[1]={...departingEntries[1],status:'finished',finished:110};await captureBoatResults(db.DB,room,departingRace,departingEntries);result=await minigameRecords(db.DB,profile);assert.equal(result.verified.boat.wins,2,'A finished racer retains the win after leaving the room before settlement');await db.DB.prepare('INSERT INTO multiplayer_players(token,room,name,state,updated) VALUES(?,?,?,?,?)').bind(at,room,oldPlayer.name,oldPlayer.state,now).run();
const save={'pawtheon-sled-best-v3':'80.5','pawtheon-tide-run-best-river-v3':'70.5','pawtheon-minigame-records-v1':JSON.stringify({sled:{bestTime:75},maze9:{bestTime:25},maze13:{bestTime:90},maze86:{bestTime:600},crossword:{bestTime:120},boat:{bestTime:68}})};assert.equal((await api('accounts/save',{accountId:a.data.user.id,revision:0,save},a.cookie)).status,200);result=(await api('accounts/minigame-records',undefined,a.cookie)).data;for(const [key,time]of Object.entries({sled:75,boatSolo:68,maze9:25,maze13:90,maze86:600,crossword:120})){assert.equal(result.savedLeaders[key][0].time,time);assert.equal(result.savedLeaders[key][0].self,true);}assert.equal(result.verified.boat.bestTime,80,'Saved solo times never enter server board');
await db.DB.prepare('DELETE FROM multiplayer_boat_entries WHERE room=?').bind(room).run();await db.DB.prepare('DELETE FROM multiplayer_lava_arenas WHERE room=?').bind(room).run();await db.DB.prepare('DELETE FROM multiplayer_players WHERE room=?').bind(room).run();db.close();db=openRoomDatabase(file);result=(await api('accounts/minigame-records',undefined,a.cookie)).data;assert.equal(result.verified.boat.bestTime,80);assert.equal(result.verified.lava.games,2);assert.equal(result.savedLeaders.boatSolo[0].time,68);assert.equal(result.chess.record.games,0);
console.log('PASS authoritative Boat/Lava finish capture; replay and posted-score rejection; ties, quits and privacy; solo/verified separation; room cleanup and database restart persistence; all saved-time boards');
}finally{db.close();await rm(dir,{recursive:true,force:true});}
