import assert from 'node:assert/strict';
import {applyShopAction,SHOP_KEY,SHARD_KEY,shopView,preserveAccountShop} from '../public/moon-shop-core.js';
import {emptyOrders,orderJourney,orderLoadout,contractRoute} from '../public/order-progression.js';
import {ORDER_IDS,orderSpells} from '../public/order-spells.js';
import {wizards} from '../public/wizards.js';import {height} from '../public/geography.js';
const dog=o=>wizards.find(w=>w.order===o).id;
let save={[SHARD_KEY]:JSON.stringify(['moon-0-0','moon-0-1','moon-0-2','moon-1-0']),'pawtheon-dog':'6164'};
let j=orderJourney(save);assert.equal(j.active,'Flame');assert.equal(j.orders.Flame.level,2);assert.equal(j.orders.Dream.level,1);assert.equal(j.overallLevel,2);assert(!j.wandererUnlocked);
save=applyShopAction(save,{operation:'order-sync',order:'Flame'});const first=save[SHOP_KEY];save=applyShopAction(save,{operation:'order-sync',order:'Flame'});assert.equal(save[SHOP_KEY],first);save['pawtheon-dog']=String(dog('Dream'));save[SHARD_KEY]=JSON.stringify(['moon-0-0','moon-0-1','moon-0-2','moon-1-0','moon-1-1']);save=applyShopAction(save,{operation:'order-sync',order:'Dream'});j=orderJourney(save);assert.equal(j.record.collectionXP.Flame,155);assert.equal(j.record.collectionXP.Dream,20);assert.equal(j.orders.Flame.level,2);assert.equal(j.orders.Dream.level,1);assert.throws(()=>applyShopAction(save,{operation:'order-sync',order:'Flame'}));
const route=contractRoute('Dream');for(let i=0;i<route.length;i++){const p=route[i],body={operation:'order-visit',order:'Dream',target:p.id,expectedCompleted:0,expectedStep:i,position:{x:p.x,y:height(p.x,p.z),z:p.z}};if(i){const shop=JSON.parse(save[SHOP_KEY]);shop.orders.contracts.Dream.lastAt=0;save[SHOP_KEY]=JSON.stringify(shop);}save=applyShopAction(save,body);assert.throws(()=>applyShopAction(save,body));}
j=orderJourney(save);assert.equal(j.orders.Dream.contract.completed,1);assert.equal(j.orders.Dream.xp,70);assert(j.overallLevel>=2);assert.equal(shopView(save).balance,5);assert.throws(()=>preserveAccountShop(save,{...save,[SHOP_KEY]:first}));
const r=emptyOrders();for(const o of ORDER_IDS)r.contracts[o].completed=80;let mastered={[SHOP_KEY]:JSON.stringify({version:1,owned:{wand:0,staff:0},equipped:null,orders:r}),'pawtheon-dog':String(dog('Flame'))};j=orderJourney(mastered);assert(j.wandererUnlocked);assert.equal(j.overallLevel,295);for(const o of ORDER_IDS){assert.equal(j.orders[o].level,50);assert.equal(orderLoadout(j,o).length,3);assert.equal(new Set(orderLoadout(j,o).map(s=>s.id)).size,3);}mastered['pawtheon-dog']='6164';j=orderJourney(mastered);assert.equal(j.active,'Wanderer');assert(orderLoadout(j).every(s=>s.tier===3));
mastered['pawtheon-dog']=String(dog('Flame'));mastered=applyShopAction(mastered,{operation:'order-upgrade',order:'Flame',item:'phoenix-stride',expectedLevel:1});assert.equal(orderJourney(mastered).record.upgrades['phoenix-stride'],2);assert.throws(()=>applyShopAction(mastered,{operation:'order-equip',order:'Flame',item:'dream-threads',slot:0}));mastered=applyShopAction(mastered,{operation:'order-equip',order:'Flame',item:'phoenix-stride',slot:0});assert.equal(orderLoadout(orderJourney(mastered))[0].id,'phoenix-stride');assert.equal(orderLoadout(orderJourney(mastered))[2],null);
assert.equal(orderSpells.length,21);assert(ORDER_IDS.every(o=>orderSpells.filter(s=>s.order===o).length===3));
console.log('PASS isolated Order XP/migration/replay, active-Order routing, repeatable contract reward, level50 caps, combined wizard295, all-six Wanderer lock, three distinct slots and upgrades');
