const {chromium}=require('/opt/homebrew/lib/node_modules/agent-browser/node_modules/playwright-core');
const assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto');
const origin='http://127.0.0.1:8065',base=origin+'/play',report={checks:[],errors:[],failedRequests:[]};
(async()=>{const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-angle=metal','--disable-background-timer-throttling','--disable-renderer-backgrounding']});try{
const a=await browser.newContext({viewport:{width:1440,height:900}}),b=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
const signup=await a.request.post(base+'/api/accounts/signup',{headers:{Origin:origin,'X-Pawtheon-Request':'1'},data:{username:'release_'+crypto.randomBytes(5).toString('hex'),password:crypto.randomBytes(24).toString('base64url'),name:'Release Explorer'}});assert.equal(signup.status(),200);
const p=await a.newPage(),q=await b.newPage();for(const page of [p,q]){page.on('pageerror',e=>report.errors.push(e.message));page.on('response',r=>{if(r.status()>=400)report.failedRequests.push({url:r.url().split('#')[0],status:r.status()})});}
await p.goto(base+'/',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>!document.querySelector('#loading'),{timeout:120000});assert(await p.locator('canvas').count());report.checks.push('Desktop WebGL solo world renders beneath /play');
await p.screenshot({path:'release-verification/desktop.png'});
await p.goto(base+'/multiplayer',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>!document.querySelector('#loading'),{timeout:120000});await p.locator('#roomLobby').waitFor({state:'visible'});assert.equal(await p.locator('#roomName').inputValue(),'Release Explorer');await p.locator('#createRoom').click();await p.waitForFunction(()=>!document.querySelector('#roomBar').hidden);const invite=await p.locator('#inviteLink').inputValue();assert(invite.startsWith(base+'/multiplayer#'));report.checks.push('Signed-in identity and private room creation use /play');
await q.goto(invite,{waitUntil:'domcontentloaded'});await q.waitForFunction(()=>!document.querySelector('#loading'),{timeout:120000});await q.locator('#roomName').fill('Mobile Explorer');await q.locator('#joinRoom').tap();await q.waitForFunction(()=>document.querySelector('#roomStatus').textContent.includes('2 / 8'));await p.waitForFunction(()=>document.querySelector('#roomStatus').textContent.includes('2 / 8'));report.checks.push('Second mobile browser joins same private room; both show 2 players');
assert(await q.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await q.screenshot({path:'release-verification/mobile.png'});await q.locator('#hudMenuBtn').tap();await q.locator('#roomBar summary').tap();await q.locator('#leaveRoom').tap();await q.waitForURL(base+'/');await q.waitForFunction(()=>!document.querySelector('#loading'),{timeout:120000});report.checks.push('Mobile viewport fits and Leave returns to /play/');
assert.deepEqual(report.errors,[]);assert.deepEqual(report.failedRequests,[]);report.passed=true;console.log(JSON.stringify(report));
}finally{await browser.close();fs.writeFileSync('release-verification/browser.json',JSON.stringify(report,null,2));}})().catch(e=>{console.error(e.message);process.exitCode=1});
