const $=id=>document.getElementById(id),preview=$('preview'),pctx=preview.getContext('2d'),native=document.createElement('canvas'),nctx=native.getContext('2d',{willReadFrequently:true});native.width=native.height=25;
const firstAnimated=SCENES.findIndex(s=>s.type==='animated');const state={scene:firstAnimated,dog:'6164',animated:true,playing:!matchMedia('(prefers-reduced-motion: reduce)').matches,scale:100,x:0,y:0,rotation:0,speed:1,frame:0,busy:false};const dogCache=new Map(),bgCache=new Map(),motionCache=new Map();const selectedByMode={still:SCENES.findIndex(s=>s.type==='still'),animated:firstAnimated};let dogImage=null,bgImage=null,loadTicket=0;
const load=src=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(Error('An artwork could not load. Please try again.'));img.src=src});
async function getDog(id){if(!dogCache.has(id))dogCache.set(id,load('assets/'+id+'.png').catch(e=>{dogCache.delete(id);throw e}));return dogCache.get(id)}
async function getBg(id){if(!bgCache.has(id))bgCache.set(id,load('assets/'+id+'.png').then(pixelBackground).catch(e=>{bgCache.delete(id);throw e}));return bgCache.get(id)}
function pixelBackground(img){
 const c=document.createElement('canvas');c.width=c.height=25;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.imageSmoothingEnabled=false;ctx.drawImage(img,0,0,25,25);const data=ctx.getImageData(0,0,25,25),pixels=[];for(let i=0;i<data.data.length;i+=4)pixels.push([data.data[i],data.data[i+1],data.data[i+2]]);
 let centers=Array.from({length:24},(_,i)=>pixels[Math.floor(i*pixels.length/24)].slice());const nearest=p=>{let best=0,min=Infinity;centers.forEach((c,i)=>{const d=(p[0]-c[0])**2+(p[1]-c[1])**2+(p[2]-c[2])**2;if(d<min){min=d;best=i}});return best};
 for(let pass=0;pass<8;pass++){const sums=centers.map(()=>[0,0,0,0]);for(const p of pixels){const sum=sums[nearest(p)];sum[0]+=p[0];sum[1]+=p[1];sum[2]+=p[2];sum[3]++}centers=centers.map((c,i)=>sums[i][3]?sums[i].slice(0,3).map(v=>Math.round(v/sums[i][3])):c)}
 pixels.forEach((p,i)=>{const col=centers[nearest(p)];for(let j=0;j<3;j++)data.data[i*4+j]=col[j];data.data[i*4+3]=255});ctx.putImageData(data,0,0);return c
}
function sceneFrames(scene,base){
 if(!motionCache.has(scene.id)){const pixels=base.getContext('2d').getImageData(0,0,25,25).data;motionCache.set(scene.id,Array.from({length:scene.frames||24},(_,frame)=>{const c=document.createElement('canvas');c.width=c.height=25;c.getContext('2d').putImageData(new ImageData(animatePixels(pixels,scene,frame*24/(scene.frames||24)),25,25),0,0);return c}))}return motionCache.get(scene.id)
}
function render(frame=0,ctx=pctx,size=1000){nctx.imageSmoothingEnabled=false;nctx.fillStyle='#162323';nctx.fillRect(0,0,25,25);if(bgImage){const scene=SCENES[state.scene];nctx.drawImage(scene?.type==='animated'?sceneFrames(scene,bgImage)[Math.floor(frame*(scene.frames||24)/48)%(scene.frames||24)]:bgImage,0,0,25,25)}
 ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,size,size);ctx.drawImage(native,0,0,size,size);if(dogImage){ctx.save();ctx.translate(size/2+state.x*size/25,size/2+state.y*size/25);ctx.rotate(state.rotation*Math.PI/180);const ds=size*state.scale/100;ctx.drawImage(dogImage,-ds/2,-ds/2,ds,ds);ctx.restore()}}
function selectedUI(){document.querySelectorAll('.scene-card').forEach(b=>{const on=state.scene===Number(b.dataset.scene);b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on))});document.querySelectorAll('.dog-card').forEach(b=>{b.classList.toggle('active',b.dataset.id===state.dog);b.setAttribute('aria-pressed',String(b.dataset.id===state.dog))});const dog=WIZARDS.find(w=>w.id===state.dog);$('chosenDog').src='assets/'+state.dog+'.png';$('dogNumber').textContent='#'+dog.id;$('dogName').textContent=dog.name;const scene=SCENES[state.scene];$('realmName').textContent=scene?scene.realm:'PAWTHEON';$('sceneName').textContent=scene?scene.name:'Your original wizard';$('description').textContent=scene?scene.detail:'The original artwork on a plain background.';updateButtons()}
function updateButtons(){$('png').disabled=state.busy||!dogImage;$('gif').disabled=state.busy||!dogImage||!bgImage||!state.animated;$('play').disabled=!state.animated||!bgImage;$('play').textContent=state.playing?'Ⅱ Pause':'▷ Play';$('play').setAttribute('aria-label',state.playing?'Pause animation':'Play animation')}
async function select(dog=state.dog,scene=state.scene){const ticket=++loadTicket;bgImage=null;dogImage=null;state.dog=dog;state.scene=scene;if(scene!==null)selectedByMode[state.animated?'animated':'still']=scene;$('loading').textContent='Opening Pawtheon…';$('loading').hidden=false;state.busy=true;updateButtons();try{const [d,b]=await Promise.all([getDog(dog),scene===null?null:getBg(SCENES[scene].id)]);if(ticket!==loadTicket)return;dogImage=d;bgImage=b;state.frame=0;render();$('loading').hidden=true;$('status').textContent='PNG 1000 × 1000 · GIF 500 × 500 · original dog artwork';}catch(e){if(ticket!==loadTicket)return;$('loading').textContent=e.message;$('status').textContent=e.message}finally{if(ticket===loadTicket){state.busy=false;selectedUI()}}}
function buildDogs(){const q=$('search').value.toLowerCase(),order=$('order').value,filtered=WIZARDS.filter(w=>(!order||w.order===order)&&(!q||(w.name+' '+w.id).toLowerCase().includes(q)));$('count').textContent=filtered.length+' dogs';$('dogGrid').replaceChildren();for(const dog of filtered){const b=document.createElement('button');b.className='dog-card';b.dataset.id=dog.id;b.title='#'+dog.id+' · '+dog.name;b.setAttribute('aria-label',b.title);const img=new Image();img.src='assets/'+dog.id+'.png';img.alt=dog.name;img.loading='lazy';const label=document.createElement('span');label.textContent='#'+dog.id;b.append(img,label);b.onclick=()=>select(dog.id);$('dogGrid').append(b)}$('noDogs').hidden=filtered.length>0;selectedUI()}
function buildScenes(){
 $('scenes').replaceChildren();$('scenes').scrollTop=0;const kind=state.animated?'animated':'still';$('sceneCount').textContent=SCENES.filter(s=>s.type===kind).length+' '+kind;
 SCENES.forEach((scene,i)=>{if((scene.type==='animated')!==state.animated)return;const b=document.createElement('button');b.className='scene-card';b.dataset.scene=i;b.innerHTML=`<canvas width="25" height="25" aria-label="${scene.name}"></canvas><span class="card-label"><strong>${scene.name}</strong><small>${scene.realm}</small></span>`;b.onclick=()=>select(state.dog,i);$('scenes').append(b);getBg(scene.id).then(c=>{if(b.isConnected){b.querySelector('canvas').getContext('2d').drawImage(scene.type==='animated'?sceneFrames(scene,c)[0]:c,0,0)}}).catch(()=>{b.querySelector('small').textContent='Artwork unavailable'})});selectedUI()
}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(t=>{const on=t===b;t.classList.toggle('active',on);t.setAttribute('aria-selected',String(on));$(t.dataset.tab).hidden=!on})});
function mode(animated){if(state.animated===animated)return;state.animated=animated;state.frame=0;for(const id of ['animated','still']){$(id).classList.toggle('active',(id==='animated')===animated);$(id).setAttribute('aria-pressed',String((id==='animated')===animated))}buildScenes();select(state.dog,selectedByMode[animated?'animated':'still'])}
$('animated').onclick=()=>mode(true);$('still').onclick=()=>mode(false);$('clear').onclick=()=>select(state.dog,null);$('play').onclick=()=>{state.playing=!state.playing;updateButtons()};$('random').onclick=()=>{reset();const available=SCENES.map((s,i)=>({s,i})).filter(({s})=>(s.type==='animated')===state.animated);select(WIZARDS[Math.floor(Math.random()*WIZARDS.length)].id,available[Math.floor(Math.random()*available.length)].i)};$('search').oninput=buildDogs;$('order').onchange=buildDogs;
function controls(){for(const key of ['scale','x','y','rotation','speed']){state[key]=Number($(key).value);$(key+'Value').textContent=state[key]+({scale:'%',rotation:'°',speed:'×'}[key]||'')}render()}
for(const id of ['scale','x','y','rotation','speed'])$(id).oninput=controls;function reset(){for(const key of ['scale','x','y','rotation','speed'])$(key).value=key==='scale'?100:key==='speed'?1:0;controls()}$('reset').onclick=reset;
async function deliver(blob,extension){const name='pawtheon-'+state.dog+'-'+(SCENES[state.scene]?.id||'plain')+'.'+extension,file=new File([blob],name,{type:blob.type});if(/iPhone|iPad|iPod/.test(navigator.userAgent)&&navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file]});return}catch(e){if(e.name==='AbortError')return}}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}
$('png').onclick=async()=>{render(state.frame);const blob=await new Promise(r=>preview.toBlob(r,'image/png'));if(blob)await deliver(blob,'png')};
$('gif').onclick=async()=>{if(state.busy)return;state.busy=true;document.querySelector('main').inert=true;updateButtons();$('status').textContent='Creating your animated GIF…';try{await new Promise(r=>setTimeout(r,30));const c=document.createElement('canvas');c.width=c.height=500;const ctx=c.getContext('2d',{willReadFrequently:true}),frames=[],count=SCENES[state.scene]?.frames||24;for(let i=0;i<count;i++){render(i*48/count,ctx,500);frames.push(ctx.getImageData(0,0,500,500).data);if(i%4===0)await new Promise(r=>setTimeout(r,0))}const bytes=encodeGIF(frames,500,500,300/(count*state.speed));await deliver(new Blob([bytes],{type:'image/gif'}),'gif');$('status').textContent='GIF ready · 500 × 500 · seamless '+(3/state.speed)+'-second loop'}catch(e){$('status').textContent='Could not create GIF: '+e.message}finally{state.busy=false;document.querySelector('main').inert=false;updateButtons()}};
let last=0;function tick(time){const interval=62.5/state.speed;if(time-last>=interval){const steps=Math.floor((time-last)/interval);last+=steps*interval;if(state.animated&&state.playing&&!state.busy){state.frame=(state.frame+steps)%48;render(state.frame);if(!$('worlds').hidden)document.querySelectorAll('.scene-card').forEach(b=>{const s=SCENES[Number(b.dataset.scene)],frames=motionCache.get(s.id);if(frames)b.querySelector('canvas').getContext('2d').drawImage(frames[Math.floor(state.frame*frames.length/48)],0,0)})}}requestAnimationFrame(tick)}
buildDogs();buildScenes();select();requestAnimationFrame(tick);
