const WIZARDS = [
  {id:'165',name:'Vanguard the Glacier Walker',order:'Flame'},{id:'246',name:'Goldburn the Solar Flame',order:'Flame'},
  {id:'986',name:'Splitforge the Dual Natured',order:'Flame'},{id:'1053',name:'Deathforge the Undying',order:'Flame'},
  {id:'1271',name:'Snowcollie the Patient Amplifier',order:'Dream'},{id:'1714',name:'Roseheart the Gentle Flame',order:'Flame'},
  {id:'1841',name:'Ember Beard the Bridge Prophet',order:'Deep'},{id:'1848',name:'Lensfire the Tiger Scholar',order:'Flame'},
  {id:'1976',name:'Frostbark the Ice Grower',order:'Wild'},{id:'1977',name:'Blackclassic the Network Walker',order:'Wild'},
  {id:'2426',name:'Blotbark the Corruption Fighter',order:'Wild'},{id:'2634',name:'Mixedsight the Paradox Prophet',order:'Deep'},
  {id:'2807',name:'Voidbloom the Visor Wearer',order:'Wild'},{id:'2855',name:'Lensheart the Scholarly Amplifier',order:'Dream'},
  {id:'3030',name:'Pureflame the Unadorned',order:'Flame'},{id:'3186',name:'Brownheart the Common Light',order:'Radiant'},
  {id:'3406',name:'Pinkmantle the Dimensional Scholar',order:'Arcane'},{id:'3417',name:'Orangeshield the Flame Prophet',order:'Deep'},
  {id:'3449',name:'Stripeheart the Bridge Walker',order:'Wild'},{id:'3479',name:'Dawnheart the Neutral Amplifier',order:'Dream'},
  {id:'3557',name:'Goldstare the Solar Prophet',order:'Deep'},{id:'3735',name:'Roseheart the Steady Bond',order:'Dream'},
  {id:'3758',name:'Deathbloom the Renewal Bringer',order:'Wild'},{id:'3826',name:'Rosefield the Wild Ember',order:'Wild'},
  {id:'4042',name:'Roseflame the Pink Eyed',order:'Flame'},{id:'4165',name:'Pearlgaze the Emotional Seer',order:'Deep'},
  {id:'4458',name:'Clearsight the Precision Revealer',order:'Radiant'},{id:'4540',name:'Blotforge the Chaos Shaper',order:'Flame'},
  {id:'4650',name:'Sandstone the Stable Amplifier',order:'Arcane'},{id:'4742',name:'Blottedmist the Chaos Seer',order:'Deep'},
  {id:'4994',name:'Whitecoat the Collie Coordinator',order:'Arcane'},{id:'5035',name:'Blizzardflame the Ice Hearted',order:'Flame'},
  {id:'5056',name:'Brownvisor the Research Director',order:'Arcane'},{id:'5177',name:'Frostgrow the Gray Endurer',order:'Wild'},
  {id:'5240',name:'Graysleep the Dream Walker',order:'Arcane'},{id:'5275',name:'Tideforge the Current Rider',order:'Flame'},
  {id:'5374',name:'Redsight the Spotted Tracker',order:'Wild'},{id:'5381',name:'Roseclassic the Pink Diplomat',order:'Radiant'},
  {id:'5516',name:'Whiteguard the Shield Prophet',order:'Deep'},{id:'5518',name:'Voidstrike the Green Eyed',order:'Flame'},
  {id:'5538',name:'Graystorm the Weather Walker',order:'Wild'},{id:'6095',name:'Dalmatianscript the Unique Scholar',order:'Arcane'},
  {id:'6135',name:'Bluevisor the Technology Prophet',order:'Deep'},{id:'6164',name:'The Wanderer',order:'Wanderer'},
  {id:'6198',name:'Ashstripe the Veil Ripper',order:'Arcane'},{id:'6203',name:'Sleepytan the Dream Revealer',order:'Radiant'},
  {id:'6232',name:'Goldsolid the Pure Prophet',order:'Deep'},{id:'6398',name:'Tideseed the Shore Walker',order:'Wild'},
  {id:'6502',name:'Sleepyheart the Dream Bonder',order:'Arcane'},{id:'6597',name:'Inkwell the Archive Prophet',order:'Deep'},
  {id:'6873',name:'Goldleaf the Multi Eyed',order:'Wild'},{id:'7226',name:'Tanwatcher the Patient Prophet',order:'Deep'},
  {id:'7257',name:'Graydreamer the Sleep Prophet',order:'Deep'},{id:'7439',name:'Goldsentry the Gentle Endurer',order:'Arcane'},
  {id:'7710',name:'Goldstrike the Lightning Fast',order:'Flame'},{id:'7731',name:'Beigelight the Steady Illuminator',order:'Radiant'},
  {id:'7770',name:'Stripesight the Pattern Burner',order:'Flame'},{id:'7833',name:'Bronzebeacon the Shiny Light',order:'Radiant'},
  {id:'8095',name:'Rosestrike the Pink Eyed',order:'Flame'},{id:'8154',name:'Grayveil the Foundation Scholar',order:'Arcane'},
  {id:'8272',name:'Spotforge the Pattern Reader',order:'Wild'},{id:'8284',name:'Stripesight the Pattern Hunter',order:'Wild'},
  {id:'8311',name:'Goldvisor the Tiger Theorist',order:'Dream'},{id:'8342',name:'Whiteheart the Split Researcher',order:'Dream'},
  {id:'8518',name:'Goldstripe the Time Stalker',order:'Dream'},{id:'8667',name:'Goldforge the Sun Touched',order:'Flame'},
  {id:'8728',name:'Frostforge the Scarf Bearer',order:'Flame'},{id:'8822',name:'Chaosbloom the Change Bringer',order:'Wild'},
  {id:'8965',name:'Brownthorn the Shield Grower',order:'Wild'},{id:'9017',name:'Sleepysteady the Gentle Dreamer',order:'Dream'},
  {id:'9025',name:'Grayheart the Split Revealer',order:'Radiant'},{id:'9089',name:'The Warlock',order:'Dream'},
  {id:'9183',name:'Whiteheart the Pink Eyed Illuminator',order:'Radiant'},{id:'9234',name:'Shadowspot the Pattern Keeper',order:'Arcane'},
  {id:'9301',name:'Rosegold the Pink Eyed Theorist',order:'Dream'},{id:'9396',name:'Tancollar the Diplomatic Light',order:'Radiant'},
  {id:'9469',name:'Whitemist the Sleepy Purifier',order:'Radiant'},{id:'9530',name:'Bernardguard the Truth Keeper',order:'Deep'},
  {id:'9604',name:"Beigelumber the Worker's Light",order:'Radiant'},{id:'9624',name:'Inkspot the Silent Decoder',order:'Arcane'},
  {id:'9684',name:'Goldblot the Luminous Shadow',order:'Radiant'},{id:'9713',name:'Darkleaf the Shadow Grower',order:'Wild'},
  {id:'9758',name:'Commonflame the Everyman',order:'Flame'},{id:'9826',name:'Greenbone the Chaos Scholar',order:'Dream'},
  {id:'9898',name:'Verdant the Arcane Flame',order:'Arcane'},{id:'9952',name:'Grimbloom the Green Eyed',order:'Wild'},
  {id:'starter-1',name:'Starter Dog 1',order:'Starter'},{id:'starter-2',name:'Starter Dog 2',order:'Starter'},
  {id:'starter-3',name:'Starter Dog 3',order:'Starter'},{id:'starter-4',name:'Starter Dog 4',order:'Starter'},
  {id:'starter-5',name:'Starter Dog 5',order:'Starter'},{id:'starter-6',name:'Starter Dog 6',order:'Starter'},
  {id:'starter-7',name:'Starter Dog 7',order:'Starter'},{id:'starter-8',name:'Starter Dog 8',order:'Starter'}
];
